//
//  PaletteIDs.h
//  libRealSpace
//
//  Created by Fabien Sanglard on 1/31/2014.
//  Copyright (c) 2014 Fabien Sanglard. All rights reserved.
//

#pragma once

#if 0

enum PaletteIDs
{
	OPTPALS_PAK_WILDCAT_CHANGEROOM_BG = 4,
	OPTPALS_PAK_WILD_CAT_HANGAR = 5,
	OPTPALS_PAK_SELECT_WEAPON_F16_AT_WILDCAT_BG = 12,
	OPTPALS_PAK_MISSION_OUTSIDE_VEHICULE_TRUCK = 14,
	OPTPALS_PAK_WC_BASE_OUTSIDE_BG = 16,
	OPTPALS_PAK_PINUP = 17,
	OPTPALS_PAK_NOTE_BOOK = 18,
	OPTPALS_PAK_SKY_PALETTE_PATCH_ID = 21,
	OPTPALS_PAK_MAP_NORTH_AMERICA = 23,
	OPTPALS_PAK_MOUTAIN_PALETTE_PATCH_ID = 24,
	OPTPALS_PAK_LAMDSTRIP_BG2 = 25,
	OPTPALS_PAK_STARTGAME_REGISTRATION = 30,
	OPTPALS_PAK_WILDCAT_CHANGEROOM_PINUP_M = 40,
};

#endif
